import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/view/Header/Header";
import Providers from "./Providers";
import Navbar from "@/view/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar/>
          <Header />
          {/* Homepage */}
          <main className="px-8 md:px-28">{children}</main>
        </Providers>
      </body>
    </html>
  );
}